### ISSUE TITLE
att_seq2seq_delete_and_copy.py 引用冲突

### ISSUE THREAD

**Issue by madeirak** [soloice/tf-tutorial#2]
我在运行 tf-tutorial/src/att_seq2seq_delete_and_copy.py 时遇到引用问题
请问这个怎么解决？？
```
Traceback (most recent call last):
  File "G:/123/src/att_seq2seq_delete_and_copy.py", line 2, in <module>
    import tensorflow as tf
  File "G:\Anaconda3\envs\DeepSpeechRecognition\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "G:\Anaconda3\envs\DeepSpeechRecognition\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "G:\Anaconda3\envs\DeepSpeechRecognition\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "G:\Anaconda3\envs\DeepSpeechRecognition\lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "G:\Anaconda3\envs\DeepSpeechRecognition\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "G:\Anaconda3\envs\DeepSpeechRecognition\lib\site-packages\numpy\core\overrides.py", line 46, in <module>
    """)
RuntimeError: implement_array_function method already has a docstring
```

**Comment by madeirak** [comment]
。。升了一下级解决了

**Comment by soloice** [comment]
解决了就好。
